name: 'Register Source'
description: 'Registers the source with the specified steps'
inputs:
  base_url:
    description: 'The base URL for the API'
    required: true
  bb_run_uuid:
    description: 'The Building Block Run UUID'
    required: true
  steps:
    description: 'The steps to register'
    required: true
  token:
    description: 'The API token for authentication'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'

